### ISSUE TITLE
Number format is wrong after saving

### ISSUE THREAD

**Issue by Andrew-Lyu** [MathNya/umya-spreadsheet#147]
When I do a cell to cell copy from one excel to another, cells of some columns got the wrong number format. 

My code is like below,
for row_num in 1..max_row {
    for col_num in 1..max_col {
        let source_cell = from_sheet.get_cell((col_num, row_num)).unwrap();
        let mut target_cell = sheet_cell.clone();
        to_sheet.set_cell(target_cell);
    }
}

after saving, cell's number format goes wrong. format code in from_sheet is Some(NumberingFormat { number_format_id: 176, format_code: "0.00_ ", is_build_in: false }), but format code in to_sheet is Some(NumberingFormat { number_format_id: 178, format_code: "[$-F800]dddd\\,\\ mmmm\\ dd\\,\\ yyyy", is_build_in: false })

**Comment by MathNya** [comment]
@Andrew-Lyu 
Thank you for your report.
It is probably a glitch in the program.
We will address this issue in the next version update.

**Comment by MathNya** [comment]
@Andrew-Lyu 
I tried to verify the operation here, but could not reproduce it.
(The code we verified is here: https://github.com/MathNya/umya-spreadsheet/commit/f54342acd85d321a250eab66e72d2b7811d907b2)
We are modifying some code for the new version.
Maybe the problem was solved in the process.
Version 1.1.0 will be released soon.
Please check again there.

**Comment by Andrew-Lyu** [comment]
Hi Math,

Actually the problem still exists, I attach full example code and excel file here, you can run and check column O and AH, the number format were changed.

Regards
[excel_number.zip](https://github.com/MathNya/umya-spreadsheet/files/13487296/excel_number.zip)

**Comment by Andrew-Lyu** [comment]
@MathNya
I think I found the root cause, not sure if my fix is totally correct (it pass my test case though), so I paste it here, for your reference.
numbering_formats.rs, from line 57. In my test case, cell B1's format id is **178**, format is "[$-F800]dddd\,\ mmmm\ dd\,\ yyyy", but the current code will write format id **176**,  this makes the cells with format 176 display the wrong format.
 
    pub(crate) fn set_style(&mut self, style: &Style) -> u32 {
        match style.get_numbering_format() {
            Some(v) => {
                let number_format_id = v.get_number_format_id();
                if v.get_is_build_in() == &true {
                    return *number_format_id;
                }
                if self.numbering_format.get(number_format_id).is_some() {
                    return *number_format_id;
                }
                let hash_code = v.get_hash_code();
                // let mut id = 175;
                for (index, numbering_format) in &self.numbering_format {
                    if numbering_format.get_hash_code() == hash_code {
                        return *index;
                    }
                    // if &id < index {
                    //     id = *index;
                    // }
                }
                // id += 1;
                let mut num = v.clone();
                // num.set_number_format_id_crate(id);
                self.set_numbering_format(num);
                // id
                *number_format_id
            }
            None => 0,
        }
    }

**Comment by MathNya** [comment]
@Andrew-Lyu 
Thanks for the information.
We have reproduced the problem here as well.
We will fix it soon.

**Comment by Andrew-Lyu** [comment]
@MathNya 
I don't understand why hard coding 175.
What I see is, the format id is different from the source file in the styles.xml, more important is, I see one format missing.
Here's number format in styles.xml from the source file
`<numFmts count="4">
<numFmt numFmtId="43" formatCode="_ * #,##0.00_ ;_ * \-#,##0.00_ ;_ * "-"??_ ;_ @_ "/>
<numFmt numFmtId="176" formatCode="0.00_ "/>
<numFmt numFmtId="177" formatCode="0.0%"/>
<numFmt numFmtId="178" formatCode="[$-F800]dddd\,\ mmmm\ dd\,\ yyyy"/>
</numFmts>`

and below is number format data in styles.xml in the generated file.
`<numFmts count="3">
<numFmt numFmtId="177" formatCode="0.00_ "/>
<numFmt numFmtId="176" formatCode="[$-F800]dddd\,\ mmmm\ dd\,\ yyyy"/>
<numFmt numFmtId="178" formatCode="0.0%"/>
</numFmts>`

you can see format 43 was missing.

**Comment by Andrew-Lyu** [comment]
I think this can be closed
