### ISSUE TITLE
Column is misspelled as "Colmun"

### ISSUE THREAD

**Issue by KyGost** [MathNya/umya-spreadsheet#40]
At least in the docs, it looks like the API for this crate misspells column; example:
https://docs.rs/umya-spreadsheet/latest/umya_spreadsheet/structs/struct.Spreadsheet.html#method.insert_new_colmun

**Comment by MathNya** [comment]
Thank you for pointing this out.
We will fix it in the next update.

**Comment by MathNya** [comment]
All subject wording has been corrected.
Please obtain and check the latest version.

**Comment by KyGost** [comment]
> All subject wording has been corrected.
> Please obtain and check the latest version.

Awesome! Will do when I get a chance.

I should have also mentioned that there was a few other linguistic errors, for example plurals where functions were singular.
I'll make a new issue if they are still present.

**Comment by KyGost** [comment]
Trying to find it on my phone via the commit log and can't at the moment, could you link it please @MathNya?

**Comment by MathNya** [comment]
Here is the link for the subject.
https://github.com/MathNya/umya-spreadsheet/commit/1d800bcb9962c92a555f35cadbaa3d94d30ef302#diff-dd720a6892aee909a8f070b837f3c74d135d1fd025ebea0ba862dfa1bb9e2d83L77-R77
https://github.com/MathNya/umya-spreadsheet/commit/1d800bcb9962c92a555f35cadbaa3d94d30ef302#diff-dd720a6892aee909a8f070b837f3c74d135d1fd025ebea0ba862dfa1bb9e2d83L98-R98
https://github.com/MathNya/umya-spreadsheet/commit/1d800bcb9962c92a555f35cadbaa3d94d30ef302#diff-dd720a6892aee909a8f070b837f3c74d135d1fd025ebea0ba862dfa1bb9e2d83L131-R131
https://github.com/MathNya/umya-spreadsheet/commit/1d800bcb9962c92a555f35cadbaa3d94d30ef302#diff-dd720a6892aee909a8f070b837f3c74d135d1fd025ebea0ba862dfa1bb9e2d83L147-R147

**Comment by KyGost** [comment]
Looks to be resolved
